### ISSUE TITLE
check_node.sh ｛port｝有报错

### ISSUE THREAD

**Issue by arsArtD** [jeanron100/mysql_mgr_test#3]
${base_dir}/bin/mysql -P${node_port} -S ${base_data_dir}${node_name}/${node_name}.sock -e "select uuid(); select *from performance_schema.replication_group_members;"
这句话有问题，应该修改为：
${base_dir}/bin/mysql -P${node_port} -S ${base_data_dir}/${node_name}/${node_name}.sock -e "select uuid(); select *from performance_schema.replication_group_members;"

**Comment by jeanron100** [comment]
我检查一下
